Added the option to hide IP addresses in logs
LOOHP/Limbo pull request #49
Opened 2022-07-10 15:46 UTC by SlenkyDev

Due to GDPR and similar laws in some countries, server owners are better off without logging IP addresses in the case that a player requests a removal of his/her data. Most modern Minecraft server software has this config option already, but as Limbo was missing it I decided to add it!

Lmk if you need anything changed before merging.

2022-07-11 15:13 UTC, xHyroM commented
cc @LOOHP

2022-07-19 06:24 UTC, LOOHP commented
Any updates on this?

2022-07-19 08:51 UTC, SlenkyDev commented
> Any updates on this?

?

2022-07-19 09:21 UTC, LOOHP commented
You didn't address my reviews

2022-07-19 09:35 UTC, SlenkyDev commented
> You didn't address my reviews

I apologise, but I don't see any reviews?

2022-07-19 09:35 UTC, SlenkyDev commented
![image](https://user-images.githubusercontent.com/71548884/179718829-1d39552b-ab9c-44a5-b072-1faff596aa61.png)

2022-07-19 09:49 UTC, LOOHP requested changes

2022-07-19 09:49 UTC, LOOHP commented on src/main/java/com/loohp/limbo/network/ClientConnection.java
> +                if(!properties.isLogPlayerIPAddresses())
I prefer the style of 
```java
if (false) {
      statement;
}
```

2022-07-19 09:50 UTC, LOOHP commented
Sorry about that. I've tried resubmitting the review now.

2022-07-23 15:01 UTC, SlenkyDev commented
Will do

2022-08-07 14:39 UTC, SlenkyDev commented
Apologies for the delay, I was busy with working on something.

2022-08-07 16:31 UTC, merged