Teach Loohp-Limbo how to login clients connecting via floodgate
LOOHP/Limbo pull request #55
Opened 2022-09-26 21:06 UTC by tadhunt

Note that in the following LOGIN traces, PII has been removed, but the traces are otherwise unaltered.  These traces are from the code in the PR, so you should be able to reproduce.  I am not sure if this matters, but in the case where no Floodgate cipher is **not** sent, the client and server are on my LAN, but in the case where it **is** sent, the client is on my LAN and the server in in the cloud.  Velocity, Geyser, Floodgate and Loop Limbo configurations are identical in both locations, and software versions are also identical.

Client is the same iPad in both cases, running Minecraft 1.19.30.

_LOGIN from client where the Floodgate cipher is not sent_:
```
[14:45:08 Info] Loaded world minecraft:world!
[14:45:08 Info] Limbo server listening on /0.0.0.0:30000
[14:46:02 Info] 0: H.H.H.H
[14:46:02 Info] 1: C.C.C.C
[14:46:02 Info] 2: 000000000000000000090XXXXXXXXXXXX
[14:46:02 Info] 3: [{"name":"textures","value":"","signature":""},{"name":"textures","value":"XXX","signature":"XXX"}]
[14:46:02 Info] Host: H.H.H.H
[14:46:02 Info] Floodgate: 
[14:46:02 Info] clientIp: C.C.C.C
[14:46:02 Info] bungee: 00000000000000000009XXXXXXXXXXXX
[14:46:02 Info] skinData: [{"name":"textures","value":"","signature":""},{"name":"textures","value":"XXX","signature":"XXX"}]
[14:46:03 Info] [/192.168.50.165:49769|*XXX(00000000-0000-0000-0009-XXX)] <-> Player had connected to the Limbo server!
```
Note that the `Floodgate:` line shows no content, and there are only 4 items in the `data` array.

*Login from client where the Floodgate cipher is sent*:
```
[21:37:08 Info] Limbo server listening on /0.0.0.0:30000
[21:37:15 Info] 0: H.H.H.H
[21:37:15 Info] 1: ^Floodgate^>XXXXXXXXXXXXXXXX+XXXXXXXXXXXXXXXXXXXXXXXX
[21:37:15 Info] 2: C.C.C.C
[21:37:15 Info] 3: 00000000000000000009XXXXXXXXXXXX
[21:37:15 Info] 4: [{"name":"textures","value":"XXX","signature":"XXX"}]
[21:37:15 Info] Host: H.H.H.H
[21:37:15 Info] Floodgate: ^Floodgate^>XXXXXXXXXXXXXXXX+XXXXXXXXXXXXXXXXXXXXXXXX
[21:37:15 Info] clientIp: C.C.C.C
[21:37:15 Info] bungee: 00000000000000000009XXXXXXXXXXXX
[21:37:15 Info] skinData: [{"name":"textures","value":"XXX","signature":"XXX"}]
[21:37:16 Info] [C.C.C.C:52168|*XXXX(00000000-0000-0000-0009-XXXXXXXXXXXX)] <-> Player had connected to the Limbo server!
```
Note that the `Floodgate:` line is not empty, and there are 5 items in the `data` array.

The old code always assumed `data[1]` contained the bungeecord provided UUID, but as we can see from the two traces, sometimes it's at `data[1]` and sometimes it's at `data[2]`

2022-09-29 19:23 UTC, LOOHP requested changes

2022-09-29 19:23 UTC, LOOHP commented on .gitignore
> +
Can you remove the `.gitignore` changes?

2022-09-29 19:23 UTC, LOOHP commented on src/main/java/com/loohp/limbo/network/ClientConnection.java
> +                                Limbo.getInstance().getConsole().sendMessage("skinData: " + skinData);
Can you make these (and the other) debug messages togglable in `server.properties`?

2022-09-29 19:23 UTC, LOOHP commented on src/main/java/com/loohp/limbo/network/ClientConnection.java
> +                                Limbo.getInstance().getConsole().sendMessage(sw.toString());
I think this can also be only showed if the debug option is enabled

2022-09-29 19:23 UTC, LOOHP commented on src/main/java/com/loohp/limbo/network/ClientConnection.java
> +                                for(int i = 0; i < data.length; i++) {
Missing a space after `for`

2022-09-29 22:23 UTC, tadhunt commented on .gitignore
> +
fixed

2022-09-29 22:24 UTC, tadhunt commented on src/main/java/com/loohp/limbo/network/ClientConnection.java
> +                                Limbo.getInstance().getConsole().sendMessage("skinData: " + skinData);
I conditionalized this on the `server.properties` `reduced-debug-info=true` setting, I wasn't sure if that's what you meant or if I should add a new debug flag?

2022-09-29 22:25 UTC, tadhunt commented on src/main/java/com/loohp/limbo/network/ClientConnection.java
> +                                Limbo.getInstance().getConsole().sendMessage(sw.toString());
I also conditionalized this on the `server.properties` `reduced-debug-info=true` flag, happy to change it if that's not what you meant.

2022-09-29 22:25 UTC, tadhunt commented on src/main/java/com/loohp/limbo/network/ClientConnection.java
> +                                for(int i = 0; i < data.length; i++) {
fixed

2022-09-30 11:45 UTC, LOOHP requested changes

2022-09-30 11:45 UTC, LOOHP commented on src/main/java/com/loohp/limbo/network/ClientConnection.java
> +                                    switch(state) {
Also a space here after `switch`

2022-09-30 11:45 UTC, LOOHP commented on src/main/java/com/loohp/limbo/network/ClientConnection.java
> +                                        if(data[i].startsWith("^Floodgate^")) {
Also a space here after `if`

2022-09-30 11:45 UTC, LOOHP commented on src/main/java/com/loohp/limbo/network/ClientConnection.java
> +                                Limbo.getInstance().getConsole().sendMessage(sw.toString());
It's ok! Thanks!

2022-09-30 11:45 UTC, LOOHP commented on src/main/java/com/loohp/limbo/network/ClientConnection.java
> +                                Limbo.getInstance().getConsole().sendMessage("skinData: " + skinData);
It's ok like this! Thanks!

2022-09-30 14:28 UTC, tadhunt commented on src/main/java/com/loohp/limbo/network/ClientConnection.java
> +                                    switch(state) {
whoops, I missed this one, thanks, fixed!

2022-09-30 14:28 UTC, tadhunt commented on src/main/java/com/loohp/limbo/network/ClientConnection.java
> +                                        if(data[i].startsWith("^Floodgate^")) {
whoops, I missed this one, thanks, fixed!

2022-09-30 14:49 UTC, merged